### ISSUE TITLE
Get username from query parameter for O365 federated requests

### ISSUE THREAD

**Issue by wadami-netbr** [pingidentity/pf-authn-js-widget#41]
When signing into Office 365 from https://portal.microsoftonline.com/, the user must enter their user@domain to be directed to the correct federation sign-on page. When reaching PingFederate using this widget the user will be required to enter their username again.
There is a workaround for this when using the HTML Form Templates, it gets the username from the request query string and do a substring to get only the username part (without @domain). https://support.pingidentity.com/s/article/Office-365-populate-HTML-Form-username
Is it possible to implement the same behavior on this widget?

Thanks.

**Comment by philipcoldrey-ping** [comment]
Thanks very much for submitting this, give us a chance to look into it a bit more and we'll get back to you with the best way forward.

**Comment by khosravian** [comment]
@wadami-netbr you can customize the templates (e.g. username_password_required.hbs file) to mimic the same modification you've done to the HTML Form templates, although I wouldn't recommend doing so, due to general maintenance issues.

I'd recommend making use of the Identifier First adapter and the policy tree to accomplish this, which is more flexible and doesn't require any code change.

Hope this helps.

**Comment by khosravian** [comment]
closing for now.
